set_property SRC_FILE_INFO {cfile:/sim2/akashl/ember-fpga/ember-genesys2.srcs/constrs_1/imports/constrs_1/imports/ember-fpga/Genesys2_EMBER.xdc rfile:../../../ember-genesys2.srcs/constrs_1/imports/constrs_1/imports/ember-fpga/Genesys2_EMBER.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVDS} [get_ports sysclk_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD12 IOSTANDARD LVDS} [get_ports sysclk_p]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T28 IOSTANDARD LVCMOS33} [get_ports sclk_led]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports sc_led]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U30 IOSTANDARD LVCMOS33} [get_ports mosi_led]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U29 IOSTANDARD LVCMOS33} [get_ports miso_led]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports rram_busy_ember_led]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports rram_busy_fpga_led]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports use_mmcm_led]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports mmcm_led]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G19   IOSTANDARD LVCMOS33 } [get_ports { use_mmcm }]; #IO_0_17 Sch=sw[0]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V29 IOSTANDARD LVCMOS33} [get_ports rst_n_out]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V30 IOSTANDARD LVCMOS33} [get_ports rram_busy_in]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V25 IOSTANDARD LVCMOS33} [get_ports mclk_pause_out]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports sc_out]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports sclk_out]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports mosi_out]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ27 IOSTANDARD LVCMOS33} [get_ports rram_busy_out]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH30 IOSTANDARD LVCMOS33} [get_ports sc_in]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS33} [get_ports mclk_pause_in]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG30 IOSTANDARD LVCMOS33} [get_ports mosi_in]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK30 IOSTANDARD LVCMOS33} [get_ports miso]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK28 IOSTANDARD LVCMOS33} [get_ports sclk_in]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V27 IOSTANDARD LVCMOS33} [get_ports trig_in_ack]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E19   IOSTANDARD LVCMOS33 } [get_ports { sa_do[9] }]; #IO_L14P_T2_SRCC_17 Sch=fmc_ha_p
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F26   IOSTANDARD LVCMOS33 } [get_ports { sa_do[4] }]; #IO_L5P_T0_16 Sch=fmc_la_p
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS33} [get_ports {sa_do[0]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports {sa_do[1]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {sa_do[10]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {sa_do[11]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {sa_do[12]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {sa_do[13]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {sa_do[14]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports {sa_do[15]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {sa_do[16]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33} [get_ports {sa_do[17]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {sa_do[18]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports {sa_do[19]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS33} [get_ports {sa_do[2]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports {sa_do[20]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {sa_do[21]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {sa_do[22]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {sa_do[23]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports {sa_do[24]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {sa_do[25]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {sa_do[26]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {sa_do[27]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {sa_do[28]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {sa_do[29]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {sa_do[3]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {sa_do[30]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {sa_do[31]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports {sa_do[32]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {sa_do[33]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports {sa_do[34]}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports {sa_do[35]}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports {sa_do[36]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports {sa_do[37]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {sa_do[38]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports {sa_do[39]}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {sa_do[40]}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {sa_do[41]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports {sa_do[42]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {sa_do[43]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports {sa_do[44]}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {sa_do[45]}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports {sa_do[46]}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports {sa_do[47]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {sa_do[5]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33} [get_ports {sa_do[6]}]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports {sa_do[7]}]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33} [get_ports {sa_do[8]}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports sa_rdy]
set_property src_info {type:XDC file:1 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks sclk_in]
set_property src_info {type:XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.200 [get_clocks sclk_in]
set_property src_info {type:XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks clk_out1_ember_fpga_clk_wiz_0] -min -add_delay 1.000 [get_ports {{sa_do[*]} sa_rdy use_mmcm rram_busy_in}]
set_property src_info {type:XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks clk_out1_ember_fpga_clk_wiz_0] -max -add_delay 2.000 [get_ports {{sa_do[*]} sa_rdy use_mmcm rram_busy_in}]
set_property src_info {type:XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {CKLD-1} -user "akashl" -desc "Clock nets generated by debug core have high fanout" -objects [get_nets {sl_iport0[1]}] -objects [get_pins {{dbg_hub/sl_iport0_o[1]} {ember_fpga_i/sl_iport0[1]}}] -strings { "512" } -timestamp "Sun Jan 29 17:33:21 GMT 2023"
set_property src_info {type:XDC file:1 line:618 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {CKLD-2} -user "akashl" -desc "Signal sclk_in is direct IO intentionally, since it does not need to go very fast" -objects [get_nets sclk_in_IBUF] -objects [get_pins {ember_fpga_i/sclk_in sclk_in_IBUF_inst/O}] -timestamp "Tue Jan 31 01:23:18 GMT 2023"
set_property src_info {type:XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "akashl" -desc "Signal fsm_go triggers async reset (should have been synchronous...)" -timestamp "Tue Jan 31 08:53:06 GMT 2023"
set_property src_info {type:XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {TIMING-17} -user "akashl" -desc "Debug core has low visibility" -objects [get_pins {ember_fpga_i/ila_0/inst/ila_core_inst/* ember_fpga_i/ila_0/inst/ila_core_inst/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/ila_core_inst/*/*/*/*/*/*/*/*/*/*}] -timestamp "Tue Jan 31 08:53:06 GMT 2023"
set_property src_info {type:XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {TIMING-28} -user "akashl" -desc "Referencing auto-derived clock is fine" -objects [get_clocks clk_out1_ember_fpga_clk_wiz_0] -timestamp "Tue Jan 31 08:53:06 GMT 2023"
