set_property SRC_FILE_INFO {cfile:/sim2/akashl/ember-fpga/ember-genesys2.srcs/constrs_1/imports/constrs_1/imports/ember-fpga/Genesys2_EMBER.xdc rfile:../../../ember-genesys2.srcs/constrs_1/imports/constrs_1/imports/ember-fpga/Genesys2_EMBER.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD12 IOSTANDARD LVDS} [get_ports sys_diff_clock_clk_p]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS25} [get_ports reset]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T28 IOSTANDARD LVCMOS25} [get_ports sclk_led]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS25} [get_ports sc_led]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U30 IOSTANDARD LVCMOS25} [get_ports mosi_led]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U29 IOSTANDARD LVCMOS25} [get_ports miso_led]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS25} [get_ports rram_busy_led]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS25} [get_ports rram_busy_fpga_led]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS25} [get_ports spien_led]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS25} [get_ports rst_n_led]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS25} [get_ports clksel]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V29 IOSTANDARD LVCMOS25} [get_ports rst_n_out]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V30 IOSTANDARD LVCMOS25} [get_ports rram_busy_in]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V25 IOSTANDARD LVCMOS25} [get_ports mclk_pause_out]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS25} [get_ports sc_out]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS25} [get_ports sclk_out]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS25} [get_ports mosi_out]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS25} [get_ports aclk]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS25} [get_ports bl_en]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS25} [get_ports bleed_en]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS25} [get_ports bsl_dac_en]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS25} [get_ports {clamp_ref[0]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS25} [get_ports {clamp_ref[1]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS25} [get_ports {clamp_ref[2]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS25} [get_ports {clamp_ref[3]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS25} [get_ports {clamp_ref[4]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS25} [get_ports {clamp_ref[5]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS25} [get_ports {di[0]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS25} [get_ports {di[1]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS25} [get_ports {di[10]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS25} [get_ports {di[11]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS25} [get_ports {di[12]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS25} [get_ports {di[13]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD LVCMOS25} [get_ports {di[14]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F28 IOSTANDARD LVCMOS25} [get_ports {di[15]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS25} [get_ports {di[16]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G29 IOSTANDARD LVCMOS25} [get_ports {di[17]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C25 IOSTANDARD LVCMOS25} [get_ports {di[18]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B23 IOSTANDARD LVCMOS25} [get_ports {di[19]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS25} [get_ports {di[2]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS25} [get_ports {di[20]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS25} [get_ports {di[21]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G27 IOSTANDARD LVCMOS25} [get_ports {di[22]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L27 IOSTANDARD LVCMOS25} [get_ports {di[23]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVCMOS25} [get_ports {di[24]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N27 IOSTANDARD LVCMOS25} [get_ports {di[25]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS25} [get_ports {di[26]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C30 IOSTANDARD LVCMOS25} [get_ports {di[27]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M23 IOSTANDARD LVCMOS25} [get_ports {di[28]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS25} [get_ports {di[29]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS25} [get_ports {di[3]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS25} [get_ports {di[30]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS25} [get_ports {di[31]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B30 IOSTANDARD LVCMOS25} [get_ports {di[32]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J28 IOSTANDARD LVCMOS25} [get_ports {di[33]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N25 IOSTANDARD LVCMOS25} [get_ports {di[34]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H27 IOSTANDARD LVCMOS25} [get_ports {di[35]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M28 IOSTANDARD LVCMOS25} [get_ports {di[36]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS25} [get_ports {di[37]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N30 IOSTANDARD LVCMOS25} [get_ports {di[38]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G30 IOSTANDARD LVCMOS25} [get_ports {di[39]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS25} [get_ports {di[4]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A30 IOSTANDARD LVCMOS25} [get_ports {di[40]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVCMOS25} [get_ports {di[41]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS25} [get_ports {di[42]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS25} [get_ports {di[43]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L30 IOSTANDARD LVCMOS25} [get_ports {di[44]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVCMOS25} [get_ports {di[45]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS25} [get_ports {di[46]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L28 IOSTANDARD LVCMOS25} [get_ports {di[47]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS25} [get_ports {di[5]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS25} [get_ports {di[6]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS25} [get_ports {di[7]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS25} [get_ports {di[8]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS25} [get_ports {di[9]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS25} [get_ports {read_dac_config[0]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A27 IOSTANDARD LVCMOS25} [get_ports {read_dac_config[1]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B28 IOSTANDARD LVCMOS25} [get_ports {read_dac_config[2]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS25} [get_ports {read_dac_config[3]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS25} [get_ports read_dac_en]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS25} [get_ports {read_ref[0]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS25} [get_ports {read_ref[1]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C27 IOSTANDARD LVCMOS25} [get_ports {read_ref[2]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS25} [get_ports {read_ref[3]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K28 IOSTANDARD LVCMOS25} [get_ports {read_ref[4]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D29 IOSTANDARD LVCMOS25} [get_ports {read_ref[5]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K29 IOSTANDARD LVCMOS25} [get_ports {rram_addr[0]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H30 IOSTANDARD LVCMOS25} [get_ports {rram_addr[1]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D27 IOSTANDARD LVCMOS25} [get_ports {rram_addr[10]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS25} [get_ports {rram_addr[11]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS25} [get_ports {rram_addr[12]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M30 IOSTANDARD LVCMOS25} [get_ports {rram_addr[13]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS25} [get_ports {rram_addr[14]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N29 IOSTANDARD LVCMOS25} [get_ports {rram_addr[15]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J29 IOSTANDARD LVCMOS25} [get_ports {rram_addr[2]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L26 IOSTANDARD LVCMOS25} [get_ports {rram_addr[3]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K30 IOSTANDARD LVCMOS25} [get_ports {rram_addr[4]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J27 IOSTANDARD LVCMOS25} [get_ports {rram_addr[5]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS25} [get_ports {rram_addr[6]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B29 IOSTANDARD LVCMOS25} [get_ports {rram_addr[7]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E30 IOSTANDARD LVCMOS25} [get_ports {rram_addr[8]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS25} [get_ports {rram_addr[9]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS25} [get_ports sa_clk]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS25} [get_ports {sa_do[0]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS25} [get_ports {sa_do[1]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS25} [get_ports {sa_do[10]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS25} [get_ports {sa_do[11]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS25} [get_ports {sa_do[12]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS25} [get_ports {sa_do[13]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS25} [get_ports {sa_do[14]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS25} [get_ports {sa_do[15]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS25} [get_ports {sa_do[16]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS25} [get_ports {sa_do[17]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS25} [get_ports {sa_do[18]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS25} [get_ports {sa_do[19]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS25} [get_ports {sa_do[2]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS25} [get_ports {sa_do[20]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS25} [get_ports {sa_do[21]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS25} [get_ports {sa_do[22]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS25} [get_ports {sa_do[23]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS25} [get_ports {sa_do[24]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS25} [get_ports {sa_do[25]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS25} [get_ports {sa_do[26]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS25} [get_ports {sa_do[27]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS25} [get_ports {sa_do[28]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS25} [get_ports {sa_do[29]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS25} [get_ports {sa_do[3]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS25} [get_ports {sa_do[30]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS25} [get_ports {sa_do[31]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS25} [get_ports {sa_do[32]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS25} [get_ports {sa_do[33]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS25} [get_ports {sa_do[34]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS25} [get_ports {sa_do[35]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS25} [get_ports {sa_do[36]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS25} [get_ports {sa_do[37]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS25} [get_ports {sa_do[38]}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS25} [get_ports {sa_do[39]}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F30 IOSTANDARD LVCMOS25} [get_ports {sa_do[4]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS25} [get_ports {sa_do[40]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS25} [get_ports {sa_do[41]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS25} [get_ports {sa_do[42]}]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS25} [get_ports {sa_do[43]}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS25} [get_ports {sa_do[44]}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS25} [get_ports {sa_do[45]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS25} [get_ports {sa_do[46]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS25} [get_ports {sa_do[47]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS25} [get_ports {sa_do[5]}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS25} [get_ports {sa_do[6]}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS25} [get_ports {sa_do[7]}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS25} [get_ports {sa_do[8]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS25} [get_ports {sa_do[9]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H29 IOSTANDARD LVCMOS25} [get_ports sa_en]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS25} [get_ports sa_rdy]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M29 IOSTANDARD LVCMOS25} [get_ports set_rst]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS25} [get_ports sl_en]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS25} [get_ports wl_dac_en]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS25} [get_ports wl_en]
set_property src_info {type:XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y29 IOSTANDARD LVCMOS33} [get_ports mclk_pause_in]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y28 IOSTANDARD LVCMOS33} [get_ports rram_busy_out]
set_property src_info {type:XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD29 IOSTANDARD LVCMOS33} [get_ports PROG_SPIEN]
set_property src_info {type:XDC file:1 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD27 IOSTANDARD LVCMOS33} [get_ports PROG_SCK]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W27 IOSTANDARD LVCMOS33} [get_ports PROG_MOSI]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W28 IOSTANDARD LVCMOS33} [get_ports PROG_MISO]
set_property src_info {type:XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W29 IOSTANDARD LVCMOS33} [get_ports PROG_SS]
set_property src_info {type:XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks sclk]
set_property src_info {type:XDC file:1 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.200 [get_clocks sclk]
set_property src_info {type:XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {CKLD-1} -user "akashl" -desc "Debug core has low visibility" -objects [get_nets {sl_iport0[1]}] -objects [get_pins {{dbg_hub/sl_iport0_o[1]} {ember_fpga_i/sl_iport0[1]}}] -strings { "512" } -timestamp "Sat Feb 11 03:21:15 GMT 2023"
set_property src_info {type:XDC file:1 line:636 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {CKLD-2} -user "akashl" -desc "SCK is direct IO intentionally" -objects [get_nets PROG_SCK_IBUF] -objects [get_pins {ember_fpga_i/PROG_SCK PROG_SCK_IBUF_inst/O}] -timestamp "Wed Feb  8 02:08:50 GMT 2023"
set_property src_info {type:XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "akashl" -desc "Signal fsm_go triggers async reset (should have been synchronous...)" -timestamp "Wed Feb  8 02:08:50 GMT 2023"
set_property src_info {type:XDC file:1 line:638 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {TIMING-17} -user "akashl" -desc "Debug core has low visibility" -objects [get_pins {ember_fpga_i/ila_0/inst/* ember_fpga_i/ila_0/inst/*/* ember_fpga_i/ila_0/inst/*/*/* ember_fpga_i/ila_0/inst/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/*/*/*/*/*/* ember_fpga_i/ila_0/inst/*/*/*/*/*/*/*/*/*/*/*}] -timestamp "Wed Feb  8 02:08:50 GMT 2023"
set_property src_info {type:XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type METHODOLOGY -id {XDCC-2} -user "akashl" -desc "Override reset IOSTANDARD so that it works" -objects [get_ports { reset }] -strings { "IOSTANDARD" } -timestamp "Fri Feb 17 19:40:24 GMT 2023"
